# Generated by Django 4.2 on 2023-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
