# Generated by Django 4.2 on 2023-05-15 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.proposal')),
            ],
        ),
        migrations.AddField(
            model_name='proposal_items',
            name='Section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.section'),
            preserve_default=False,
        ),
    ]
